#!/bin/bash
# GIGBOX Audio Hotplug Handler - Stable Device Naming
# SPOOKI INSTRUMENTS - GIGBOX
# Called by udev when audio devices are added/removed
# Updates ALSA configuration for stable device references

CARD="$1"
ACTION="$2"

LOG_FILE="/var/log/gigbox-audio-hotplug.log"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

log "Audio hotplug: card=$CARD action=$ACTION"

# Wait a moment for ALSA to settle
sleep 1

# List current audio cards
log "Current audio cards:"
cat /proc/asound/cards >> "$LOG_FILE" 2>&1

find_card() {
    awk -v pattern="$1" 'tolower($0) ~ pattern { print $1; exit }' /proc/asound/cards 2>/dev/null
}

PCM_CARD=$(find_card 'hifiberry|iqaudio|rpi.?dac|bcm2835.?i2s|i2s')
USB_CARD=$(find_card 'usb|audio.*device')

# If only one class of device exists, it is the usable fallback for both roles.
if [ -z "$PCM_CARD" ] && [ -n "$USB_CARD" ]; then PCM_CARD="$USB_CARD"; fi
if [ -z "$USB_CARD" ] && [ -n "$PCM_CARD" ]; then USB_CARD="$PCM_CARD"; fi
if [ -z "$PCM_CARD" ]; then PCM_CARD=0; fi
if [ -z "$USB_CARD" ]; then USB_CARD="$PCM_CARD"; fi

log "Selected PCM card $PCM_CARD and USB card $USB_CARD"

cat > /etc/gigbox/asound-auto.conf <<EOF
# Generated by gigbox-audio-hotplug.sh. Do not edit.
pcm.gigbox_pcm_dac_hw { type hw; card $PCM_CARD; device 0 }
ctl.gigbox_pcm_dac_hw { type hw; card $PCM_CARD }
pcm.gigbox_usb_dac_hw { type hw; card $USB_CARD; device 0 }
ctl.gigbox_usb_dac_hw { type hw; card $USB_CARD }
pcm.gigbox_usb_mic_hw { type hw; card $USB_CARD; device 0 }
pcm.gigbox_main { type plug; slave.pcm "gigbox_pcm_dac_hw" }
pcm.gigbox_headphones { type plug; slave.pcm "gigbox_usb_dac_hw" }
pcm.gigbox_mic { type plug; slave.pcm "gigbox_usb_mic_hw" }
pcm.!default { type plug; slave.pcm "gigbox_main" }
ctl.!default { type hw; card $PCM_CARD }
pcm.zynthian_out { type plug; slave.pcm "gigbox_main" }
pcm.zynthian_in { type plug; slave.pcm "gigbox_mic" }
EOF

PCM_DAC_PRESENT=false
USB_DAC_PRESENT=false
[ -n "$(find_card 'hifiberry|iqaudio|rpi.?dac|bcm2835.?i2s|i2s')" ] && PCM_DAC_PRESENT=true
[ -n "$(find_card 'usb|audio.*device')" ] && USB_DAC_PRESENT=true

if [ "$ACTION" = "add" ]; then
    log "Audio device added: $CARD"
    
    if [ "$USB_DAC_PRESENT" = true ]; then
        log "USB audio device now available"
    fi
    
elif [ "$ACTION" = "remove" ]; then
    log "Audio device removed: $CARD"
    
    if [ "$USB_DAC_PRESENT" = false ]; then
        log "No USB audio devices remaining - using PCM DAC only"
    fi
fi

# Trigger Zynthian audio refresh via D-Bus if available
if command -v dbus-send >/dev/null 2>&1; then
    dbus-send --system --dest=org.zynthian.Audio --type=method_call /org/zynthian/Audio org.zynthian.Audio.RefreshDevices 2>/dev/null || true
fi

# Also trigger via systemd if alsa-restore is available
systemctl reload alsa-state 2>/dev/null || true

exit 0
